[package]
name = "lifeclick"
version = "0.1.0"
authors = ["Amos Wenger <amoswenger@gmail.com>"]
edition = "2018"

[dependencies]
yew = "0.6.0"
stdweb = "0.4.16"
num-format = "0.4.0"
indexmap = "1.0.2"
lazy_static = "1.3.0"
indoc = "0.3.3"